numpy:
  # Numpy version 1.13 introduced an important bug fix that lets quaternion
  # work correctly.  Moreover, the C-API tends to change, so each version after
  # 1.13 with a different C-API version should be supported.
  - 1.13
  - 1.14
