max_py_ver: '37'

travis:
  secure:
    BINSTAR_TOKEN: aPlAd3wLnlSWKbVOG5N+OjaZPnlNL/jeJAl/eQqkY88VUwxh6K3p84V2H1I1xRnj1IPs6jujypUAaXp5GVJX/hb6cdUozbbs1abnH54eB1d6MifN081FX2lhYaBlD+lM8/IQRUXhxu0sXie/VnHCUs7Iof/jfNkPJkjmD19I9aEKLjPUsnHnY+cKdXD9MOCIHPzTG4KwR21EKNqYy+YEznEmLpB/dD23OBT91oaV2TVWhoJI3SI9kRiOL+S5pblo9FptCj502SfgWRF3L8Xtl/DRJiwuOl8nPFh17flaITwTWL/Qz4Q6xStNjjCh0eeKu4XXFJ9r3LVDIzyQUAihoMcobM5wdrFtwllPT31pmO4z9X/vjfn0FqGq6asqK4fESMif6y1UwhxM3IM0Ohwj5tsYXxCxAHgo1aPouaHVT1WMmqqzEi4ATZGe7Bk7KIsecD2RKBYE23loNaf05dlcifNZS9F7p5nAea/q4eOCii04VFYHMWvcNm4yX9kthDuOdEBVvFuh7hRxjZbH/e6Hmyl6i1F8PjLK/q8jYGCDqacmG9Sgcv7VOKM3trhG4um8/hy3XqzAQhryLeu8qo/baL8cilZqG+xeb7BShe3F8lRfCfL6x+dKXLATOLXqxuqIOhl7TLbVsZhLXVKAAtzc/aCNTVfo47UPGtFH/4E84bk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
